"""empty message

Revision ID: 33e7669e92bb
Revises: 3d72134e7dcb
Create Date: 2022-05-22 18:06:52.181138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e7669e92bb'
down_revision = '3d72134e7dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zamowienie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_zamowienia', sa.DateTime(), nullable=True),
    sa.Column('kwota_zamowienia', sa.Float(), nullable=True),
    sa.Column('status_zamowienia', sa.String(), nullable=True),
    sa.Column('id_klienta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_klienta'], ['uzytkownicy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('szczegoly_zamowienia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zamowienia', sa.Integer(), nullable=True),
    sa.Column('id_filmu', sa.Integer(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_filmu'], ['filmy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_zamowienia'], ['zamowienie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('szczegoly_zamowienia')
    op.drop_table('zamowienie')
    # ### end Alembic commands ###
