"""empty message

Revision ID: 3fba181f5f93
Revises: f3f9afa70a86
Create Date: 2022-05-22 12:27:27.783641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fba181f5f93'
down_revision = 'f3f9afa70a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gatunek',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filmy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tytul', sa.String(length=50), nullable=True),
    sa.Column('gatunek_id', sa.Integer(), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('ocena', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gatunek_id'], ['gatunek.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmy')
    op.drop_table('gatunek')
    # ### end Alembic commands ###
