"""empty message

Revision ID: fe77d9b2e492
Revises: d60a1f66bbd2
Create Date: 2022-05-23 14:46:39.677255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe77d9b2e492'
down_revision = 'd60a1f66bbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'uzytkownicy', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uzytkownicy', type_='unique')
    # ### end Alembic commands ###
